import { ethers, network } from 'hardhat'
import { saveDeployment } from '../tasks/utils'
import * as fs from 'fs'
import * as path from 'path'

async function main() {
  console.log('\n========================================')
  console.log('Redeploy ReputationRegistry (allowForDecryption fix)')
  console.log('========================================\n')

  const [deployer] = await ethers.getSigners()
  console.log(`Deployer:  ${deployer.address}`)
  console.log(`Balance:   ${ethers.formatEther(await ethers.provider.getBalance(deployer.address))} ETH`)
  console.log(`Network:   ${network.name}\n`)

  const ReputationRegistry = await ethers.getContractFactory('ReputationRegistry')
  const registry = await ReputationRegistry.deploy(
    deployer.address,
    90 * 24 * 60 * 60,
    2
  )
  await registry.waitForDeployment()
  const addr = await registry.getAddress()
  console.log(`ReputationRegistry deployed: ${addr}`)

  saveDeployment(network.name, 'ReputationRegistry', addr)
  console.log('Deployment address saved to deployments JSON\n')

  // Re-wire existing contracts
  const depPath = path.join(__dirname, '../deployments', `${network.name}.json`)
  const deploys = JSON.parse(fs.readFileSync(depPath, 'utf-8'))

  const engineAddr = deploys['EncryptedCreditEngineV3']
  const poolAddr = deploys['PrivateLoanPoolV3']
  const delegAddr = deploys['CreditDelegationV2']

  if (engineAddr) {
    await registry.setIntegrationContract(engineAddr)
    console.log(`  ✓ Engine ${engineAddr} authorized in new ReputationRegistry`)
  }
  if (poolAddr) {
    await registry.setIntegrationContract(poolAddr)
    console.log(`  ✓ Pool ${poolAddr} authorized in new ReputationRegistry`)
  }
  if (delegAddr) {
    await registry.setIntegrationContract(delegAddr)
    console.log(`  ✓ Delegation ${delegAddr} authorized in new ReputationRegistry`)
  }

  // Update frontend .env.local
  const frontendEnvPath = path.join(__dirname, '../frontend/.env.local')
  const chainId = network.config.chainId ?? 421614
  const rpcUrl = (network.config as any).url ?? 'https://sepolia-rollup.arbitrum.io/rpc'
  const blockExplorer = 'https://sepolia.arbiscan.io'

  const frontendEnvContent = `# Auto-generated by deploy-reputation-registry.ts on ${new Date().toISOString()}
# Network: ${network.name} (chainId: ${chainId})

# Network
VITE_CHAIN_ID=${chainId}
VITE_RPC_URL=${rpcUrl}
VITE_BLOCK_EXPLORER=${blockExplorer}

# Wave 3 Contracts
VITE_CREDIT_ENGINE_V3_ADDRESS=${deploys['EncryptedCreditEngineV3'] || ''}
VITE_LOAN_POOL_V3_ADDRESS=${deploys['PrivateLoanPoolV3'] || ''}
VITE_DELEGATION_V2_ADDRESS=${deploys['CreditDelegationV2'] || ''}
VITE_REPUTATION_REGISTRY_ADDRESS=${addr}

# Wave 4 Contracts
VITE_GOVERNANCE_ADDRESS=${deploys['ScoreGatedGovernance'] || ''}
VITE_CREDIT_NFT_ADDRESS=${deploys['SoulboundCreditNFT'] || ''}

# Wave 5 Contracts
VITE_MULTI_ASSET_LOAN_POOL_ADDRESS=${deploys['MultiAssetLoanPool'] || ''}
VITE_CROSS_CHAIN_CREDIT_BRIDGE_ADDRESS=${deploys['CrossChainCreditBridge'] || ''}

# Wave 1 Contracts (kept for reference)
VITE_SIMPLE_CREDIT_ENGINE_ADDRESS=0x749663A4B343846a7C02d14F7d15c72A2643b02B
VITE_LOAN_POOL_ADDRESS=0x0A2AB73CB8311aFD261Ab92137ff70E9Ca268d69
VITE_DELEGATION_ADDRESS=0xA97c943555E92b7E8472118A3b058e72edcDC694
`

  fs.writeFileSync(frontendEnvPath, frontendEnvContent)
  console.log(`\n  ✓ Frontend .env.local written: ${frontendEnvPath}`)

  console.log('\n========================================')
  console.log('ReputationRegistry redeploy complete!')
  console.log(`New address: ${addr}`)
  console.log('========================================\n')
}

main().catch(err => {
  console.error(err)
  process.exitCode = 1
})
